#!/usr/bin/env python

import sys

from rqt_gui.main import Main
from rqt_dome_interface.dome_interface_dashboard import DomeDashboard

plugin = 'rqt_dome_interface'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))#, plugin_argument_provider=Dot.add_arguments))
